# Generated by Django 6.0.7 on 2026-07-09 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_futureprediction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futureprediction',
            name='user',
        ),
    ]
